---
title: "Plotly Examples"
author: "Chuyuan XU"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Make interactive csatterplot!
```{r}
nyc_airbnb |>
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating)
  ) |>
  plot_ly(
    x = ~lat, y=~long, color = ~price,
    text = ~label,
    type ="scatter", mode = "markers",
    alpha = .5
  )
```

Let's make box plot

```{r}
nyc_airbnb |>
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |>
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```


barchart
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |>
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  )
```

